# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-22 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeName', models.CharField(db_column='grade_name', max_length=50, unique=True)),
                ('studentNum', models.IntegerField(db_column='student_num')),
                ('girlNum', models.IntegerField(db_column='girls_num')),
                ('boyNum', models.IntegerField(db_column='boy_num')),
                ('createTime', models.DateTimeField(auto_now_add=True, db_column='create_time')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(db_column='student_name', max_length=20)),
                ('sAge', models.IntegerField(db_column='age')),
                ('sGender', models.BooleanField(db_column='gender', default=True)),
                ('sScore', models.IntegerField(db_column='score')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('sGrade', models.ForeignKey(db_column='grade', on_delete=django.db.models.deletion.CASCADE, to='interFace.Grades')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'students',
            },
        ),
    ]
